# Generated by Django 3.2.6 on 2021-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='none', max_length=1000)),
                ('id_gara', models.CharField(default='none', max_length=1000)),
                ('criterio_aggiudicazione', models.CharField(default='none', max_length=1000)),
                ('codice_istat_stazione_appaltante', models.CharField(default='none', max_length=1000)),
                ('luogo_esecuzione_nuts', models.CharField(default='none', max_length=1000)),
                ('denominazione_stazione_appaltante', models.CharField(default='none', max_length=1000)),
                ('oggetto_lotto', models.CharField(default='none', max_length=1000)),
                ('imp_lotto_netto_sicurezza', models.CharField(default='none', max_length=1000)),
                ('url_bando', models.TextField(default='none')),
                ('classifica', models.CharField(default='none', max_length=1000)),
                ('data_scadenza_bando', models.CharField(default='none', max_length=1000)),
                ('provincia_stazione_appaltante', models.CharField(default='none', max_length=1000)),
                ('la_sa_agisce_per_conto_di_altro_soggetto', models.CharField(default='none', max_length=1000)),
                ('settore', models.CharField(default='none', max_length=1000)),
                ('numero_gara_anac', models.CharField(default='none', max_length=1000)),
                ('oggetto_della_gara', models.CharField(default='none', max_length=1000)),
                ('categoria_prevalente', models.CharField(default='none', max_length=1000)),
                ('somma_urgenza', models.CharField(default='none', max_length=1000)),
                ('imp_sicurezza', models.CharField(default='none', max_length=1000)),
                ('tipo_procedura', models.CharField(default='none', max_length=1000)),
                ('luogo_esecuzione_istat', models.CharField(default='none', max_length=1000)),
                ('cf_rup', models.CharField(default='none', max_length=1000)),
                ('num_tot_lotti', models.CharField(default='none', max_length=1000)),
                ('nr_lotto', models.CharField(default='none', max_length=1000)),
                ('id_lotto', models.CharField(default='none', max_length=1000)),
                ('data_pubblicazione_scp', models.DateTimeField(auto_now_add=True)),
                ('tipo_appalto', models.CharField(default='none', max_length=1000)),
                ('soggetto_per_cui_agisce_la_sa', models.CharField(default='none', max_length=1000)),
                ('rup', models.CharField(default='none', max_length=1000)),
                ('data_pubblicazione_bando', models.DateTimeField(auto_now_add=True)),
                ('cig', models.CharField(default='none', max_length=1000)),
                ('cup', models.CharField(default='none', max_length=1000)),
                ('modalita_realizzazione', models.CharField(default='none', max_length=1000)),
                ('cpv', models.CharField(default='none', max_length=1000)),
                ('codice_fiscale_stazione_appaltante', models.CharField(default='none', max_length=1000)),
                ('imp_lotto', models.CharField(default='none', max_length=1000)),
                ('importo_gara', models.CharField(default='none', max_length=1000)),
                ('ufficio', models.CharField(default='none', max_length=1000)),
                ('Bandi_di_Gara', models.FileField(blank=True, null=True, upload_to='files')),
                ('documentazione_aggiuntiva', models.FileField(blank=True, null=True, upload_to='files')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
