# Generated by Django 3.2.6 on 2021-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210806_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='importo_gara',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
