# Generated by Django 3.2.6 on 2021-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_data_importo_gara'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gara', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('cig', models.CharField(max_length=1000)),
                ('Aescrizione_Appalto', models.CharField(max_length=1000)),
                ('Tipologia_di_Appalto', models.CharField(max_length=1000)),
                ('ammount', models.CharField(max_length=1000)),
                ('Criterio_di_aggiudizazione', models.CharField(max_length=1000)),
                ('Scadenza_ricezione_Offerte', models.CharField(max_length=1000)),
                ('Data_e_ora_apertura_offerte', models.CharField(max_length=1000)),
                ('rup', models.CharField(max_length=1000)),
                ('Nome_Stazione_Appaltante', models.CharField(max_length=1000)),
                ('Location', models.CharField(max_length=1000)),
                ('Categoria_di_servizi_o_fornitura', models.CharField(max_length=1000)),
                ('Categoria_di_Lavori', models.CharField(max_length=1000)),
                ('Attachment_file', models.FileField(upload_to='files')),
                ('Other_attachment_file', models.FileField(upload_to='files')),
            ],
        ),
    ]
