# Generated by Django 3.2.6 on 2021-08-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_m_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_datas',
            name='Aescrizione_Appalto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Categoria_di_Lavori',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Categoria_di_servizi_o_fornitura',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Criterio_di_aggiudizazione',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Data_e_ora_apertura_offerte',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Nome_Stazione_Appaltante',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Other_attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Scadenza_ricezione_Offerte',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Tipologia_di_Appalto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='ammount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='cig',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='id_gara',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='rup',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
