# Generated by Django 3.2.6 on 2021-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210812_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_datas',
            name='Data_e_ora_apertura_offerte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
