# Generated by Django 3.2.6 on 2021-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210812_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='m_datas',
            name='Categoria_di_Lavori',
        ),
        migrations.AddField(
            model_name='m_datas',
            name='Categoria_di_Lavori',
            field=models.ManyToManyField(blank=True, null=True, to='core.Categorie'),
        ),
    ]
