# Generated by Django 3.2.6 on 2021-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210813_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_datas',
            name='Categoria_di_Lavori',
            field=models.ManyToManyField(to='core.Categorie'),
        ),
    ]
