# Generated by Django 3.2.6 on 2021-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210813_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stazioni_Appaltanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natura_giuridica_codice', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_inizio', models.CharField(blank=True, max_length=1000, null=True)),
                ('stato', models.CharField(blank=True, max_length=1000, null=True)),
                ('indirizzo_odonimo', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_fine', models.CharField(blank=True, max_length=1000, null=True)),
                ('provincia_codice', models.CharField(blank=True, max_length=1000, null=True)),
                ('citta_nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('flag_inHouse', models.CharField(blank=True, max_length=1000, null=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=1000, null=True)),
                ('codice_ausa', models.CharField(blank=True, max_length=1000, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=1000, null=True)),
                ('flag_partecipata', models.CharField(blank=True, max_length=1000, null=True)),
                ('soggetto_estero', models.CharField(blank=True, max_length=1000, null=True)),
                ('denominazione', models.CharField(blank=True, max_length=1000, null=True)),
                ('provincia_nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('citta_codice', models.CharField(blank=True, max_length=1000, null=True)),
                ('cap', models.CharField(blank=True, max_length=1000, null=True)),
                ('natura_giuridica_descrizione', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='m_datas',
            name='Nome_Stazione_Appaltante',
        ),
        migrations.AddField(
            model_name='m_datas',
            name='Nome_Stazione_Appaltante',
            field=models.ManyToManyField(to='core.Stazioni_Appaltanti'),
        ),
    ]
