# Generated by Django 3.2.6 on 2021-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210813_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='m_datas',
            name='Tipologia_di_Appalto',
            field=models.CharField(blank=True, choices=[('Lavori', 'Lavori'), ('Servizi', 'Servizi'), ('Forniture', 'Forniture')], max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='m_datas',
            name='ammount',
        ),
        migrations.AddField(
            model_name='m_datas',
            name='ammount',
            field=models.ManyToManyField(to='core.Amount'),
        ),
    ]
