# Generated by Django 3.2.6 on 2021-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210813_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cig', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='m_datas',
            name='cig',
        ),
        migrations.AddField(
            model_name='m_datas',
            name='cig',
            field=models.ManyToManyField(to='core.Cig'),
        ),
    ]
