# Generated by Django 3.2.6 on 2021-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210814_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_datas',
            name='Criterio_di_aggiudizazione',
            field=models.CharField(blank=True, choices=[('Offerta economicamente più Vantaggiosa', 'Offerta economicamente più Vantaggiosa'), ('Minor Presso', 'Minor Presso'), ('Prezzo Più Basso', 'Prezzo Più Basso')], max_length=1000, null=True),
        ),
    ]
